version: '3.8'

services:
  db:
    image: mysql:8.3
    container_name: hotel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hotel
    ports:
      - "3306:3306"
    volumes:  
      - db_data:/var/lib/mysql

volumes:
  db_data:

